const wordBank = [
  { answer: 'Witness Fitness', description: 'Someone observing physical training' },
  { answer: 'Atomic Comic', description: 'An immeasurably small professional joker' },
  { answer: 'Cricket Picket', description: 'A group protesting a rhythmic chirping insect' },
  { answer: 'Locket Rocket', description: 'An ornamental accessory containing its own propellant' },
  { answer: 'Bumper Jumper', description: 'A car’s protective guard that leaps' },
  { answer: 'Candle Handle', description: 'Wax light with something to grip' },
  { answer: 'Dollar Scholar', description: 'Money-minded academic' },
  { answer: 'Finger Singer', description: 'A tiny performer or a hand vocalizer' },
  { answer: 'Garden Pardon', description: 'Forgiveness found among plants' },
  { answer: 'Hammer Clammer', description: 'A noisy tool and a shellfish' },
  { answer: 'Iron Lion', description: 'A strong metal feline' },
  { answer: 'Jelly Belly', description: 'A soft stomach or candy core' },
  { answer: 'Kitten Mitten', description: 'A young cat’s hand covering' },
  { answer: 'Leather Feather', description: 'Soft plume made of hide' },
  { answer: 'Mango Tango', description: 'A tropical fruit dance' },
  { answer: 'Noodle Poodle', description: 'Curly-haired pasta dog' },
  { answer: 'Oven Coven', description: 'A witch group that bakes' },
  { answer: 'Paper Taper', description: 'A thin sheet that shrinks' },
  { answer: 'Quilt Guilt', description: 'A warm blanket of remorse' },
  { answer: 'Ribbon Sibbon', description: 'Decorative strip and a made-up rhyme' },
  { answer: 'Sail Mail', description: 'Letters carried by boat' },
  { answer: 'Table Fable', description: 'Furniture with a story' },
  { answer: 'Unicorn Popcorn', description: 'Mythical snack food' },
  { answer: 'Velvet Helmet', description: 'Soft head protection' },
  { answer: 'Whistle Thistle', description: 'A sound and a prickly plant' },
  { answer: 'Xenon Tenon', description: 'A rare gas joint' },
  { answer: 'Yacht Caught', description: 'A luxury boat that was captured' },
  { answer: 'Zebra Debra', description: 'Striped animal and a woman’s name' },
  { answer: 'Bubble Trouble', description: 'Foamy difficulty' },
  { answer: 'Castle Hassle', description: 'Fortress with problems' },
  { answer: 'Doodle Poodle', description: 'A scribble and a dog breed' },
  { answer: 'Echo Gecko', description: 'Repeated sound and a small lizard' },
];
