const wordBank = [
  { answer: 'Bumper Jumper', description: 'Someone who leaps on a vehicles protective guard'},
  { answer: 'Candle Handle', description: 'A place to firmly grip a wax-bound light' },
  { answer: 'Dollar Scholar', description: 'An academic of coins and bills' },
  { answer: 'Hammer Clammer', description: 'A heavy-headed tool providing confused noise' },
  { answer: 'Leather Feather', description: 'A soft plume made of hide' },
  { answer: 'Mango Tango', description: 'A tropical fruit dance' },
  { answer: 'Noodle Poodle', description: 'Curly-haired pasta dog' },
  { answer: 'Oven Coven', description: 'A witch group that bakes' },
  { answer: 'Paper Taper', description: 'A thin sheet that shrinks at one end' },
  { answer: 'Quilt Guilt', description: 'A blanket of remorse' },
  { answer: 'Fail Mail', description: 'Letters unsuccessful in their goal' },
  { answer: 'Table Fable', description: 'Furniture with a story' },
  { answer: 'Velvet Helmet', description: 'Soft head protection' },
  { answer: 'Whistle Thistle', description: 'A clear and high-pitched prickly plant' },
  { answer: 'Bubble Trouble', description: 'Foamy difficulty' },
  { answer: 'Castle Hassle', description: 'Fortress of inconvenience' },
   { answer: 'Echo Gecko', description: 'A reflective sounding lizard' },
];
